#
# 'auths' schema
#
auths:
  relationships:
    has_many:
      - projects

#
# 'projects' schema
#
projects:
  attributes:
    - name: name
      type: string
      required: true
    - name: description
      type: string
      required: true
    - name: highlight
      type: boolean
      default: false
  relationships:
    belongs_to:
      - auth
    has_many:
      - comments

#
# 'comments' schema
#
comments:
  attributes:
    - name: text
      type: string
  relationships:
    belongs_to:
      - auth
