title: "hook-admin"

credentials:
  endpoint: http://hook.ddll.co/
  app_id: 17
  key: 8521120d9e5c7473229f036f6381a886

collections:
  projects:
    label: Projetos

    menu:
      icon: file
      order: 1

    dashboard:
      title: Últimos projetos
      sort: ['_id', 'desc'] # isn't working
      fields: ['name']
      limit: 5

    list:
      description: Hello there!
      actions: ['show', 'edit', 'delete']
      fields: ['name', 'client_name']
