title: "hook-admin"

credentials:
  endpoint: http://localhost:4665/
  app_id: 3
  key: 94eecceccc3f5c2a077deb1a1b6c9777

collections:

  projects:
    label: Projetos

    filters:
      - name
      - client_name

    menu:
      icon: file
      order: 1

    dashboard:
      title: Últimos projetos
      sort: ['_id', 'desc'] # isn't working
      fields: ['name']
      limit: 5

    list:
      description: Hello there!
      actions: ['show', 'edit', 'delete']
      fields: ['name', 'client_name', 'auth']
