title: "hook-admin"

collections:
  auths:
    label_field: email

  projects:
    label: My projects
    filters:
      - field: name
        type: like
      - field: highlight
        label: With highlight
    sort:
      highlights: asc

    menu:
      icon: file
      order: 1

    dashboard:
      title: Last projects
      sort: ['_id', 'desc'] # isn't working
      fields: ['name']
      limit: 5

    list:
      description: Hello there!
      actions: ['show', 'edit', 'delete']
      # fields: ['name', 'client_name', 'auth']
